INSERT INTO positions (position_name, id_sector) VALUES
    ('Ride Operator', 1),
    ('Senior Ride Operator', 1),
    ('Ride Supervisor', 1),
    ('Maintenance Technician', 2),
    ('Senior Maintenance Technician', 2),
    ('Electrical Technician', 2),
    ('Mechanical Technician', 2),
    ('Technical Inspector', 2),
    ('Ride Safety Engineer', 2),
    ('Facility Manager', 3),
    ('Cleaning Supervisor', 3),
    ('Maintenance Support Worker', 3),
    ('Safety Inspector', 4),
    ('Health & Safety Officer', 4),
    ('Compliance Coordinator', 4),
    ('Security Guard', 5),
    ('Senior Security Officer', 5),
    ('Casino Security Supervisor', 5),
    ('First Aid Responder', 6),
    ('Paramedic', 6),
    ('Medical Supervisor', 6),
    ('Restaurant Staff', 7),
    ('Cook', 7),
    ('Kitchen Supervisor', 7),
    ('Bar Staff', 7),
    ('Shop Assistant', 8),
    ('Retail Supervisor', 8),
    ('Entertainer', 9),
    ('Show Coordinator', 9),
    ('VR Attraction Operator', 9),
    ('HR Specialist', 10),
    ('Payroll Specialist', 11),
    ('IT Support Technician', 12),
    ('System Administrator', 12),
    ('Marketing Coordinator', 13),
    ('Park Operations Manager', 1);